from __future__ import annotations

from packbin._errors import ShortPacket, TrailingBytes, TypeMismatch, UnpackResult
from packbin._nodes import (
    be,
    bits,
    packed,
    times,
    bool as bool,
    bytes as bytes,
    dict as dict,
    eq,
    flags,
    flag_byte,
    group,
    i8,
    i16,
    i32,
    i64,
    f32,
    f64,
    list as list,
    repeat,
    sized,
    u2,
    u8,
    u16,
    u32,
    u64,
    utf8,
    when,
)
from packbin._scheme import BinaryPacker, Scheme
from packbin._session import PackSession

# bool, bytes, dict and list are importable by name (`as` re-exports them) but left out of `*`:
# a star import would replace the caller's builtins with field builders.
__all__ = [
    "BinaryPacker",
    "PackSession",
    "Scheme",
    "ShortPacket",
    "TrailingBytes",
    "TypeMismatch",
    "UnpackResult",
    "u8",
    "u16",
    "u32",
    "u64",
    "i8",
    "i16",
    "i32",
    "i64",
    "f32",
    "f64",
    "be",
    "flags",
    "flag_byte",
    "eq",
    "when",
    "repeat",
    "group",
    "sized",
    "u2",
    "bits",
    "packed",
    "times",
    "utf8",
]
